### ISSUE TITLE
LUKS error when partitioning Rocky 9.2

### ISSUE THREAD

**Issue by mendes-jv** [AGolz/Born2beRoot#1]

**Comment by AGolz** [comment]
When using the command "cryptsetup luksFormat /dev/sda5", LUKS2 is used by default, which can cause encryption errors. If you encounter a similar problem, use LUKS1 forcibly "cryptsetup luksFormat --type luks1 /dev/sda5"

**Comment by mendes-jv** [comment]
The behaviour i am issuing is when using luks1 with --type

When finishing part 5 of anaconda It says i need to set an encryption Key do luks device, should i do the system_devices=0 config before finishing installation?

**Comment by AGolz** [comment]
Try specifying luks2, but it's strange since luks2 encryption errors are known, luks1 should not lead to problems. Check that you are applying encryption to the expanded block, and not to primary. Check if you made any mistakes when splitting the disk, correctly performed the previous steps. It's hard to say what the problem is remotely, encryption errors are very dependent on the system, machine, etc.

It is better to change the configuration "system_devices=0" later, so as not to provoke additional errors when installing the system.

**Comment by AGolz** [comment]
And try to install the Rocky 9.1 version, it is more stable. You can upgrade the system to 9.2 after installation using dnf.

**Comment by mendes-jv** [comment]
It only works when installing with 9.1 
9.2 installation get luks encryption error
i'll try to update after full install, thx for the help and for your repo, it is really helping me out!

**Comment by AGolz** [comment]
I'm really glad it helps you.
